Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -43,16 +43,26 @@ jobs:
   unusedexports:
     name: Find unused exports (desd code)
     runs-on: ubuntu-latest
-    needs: run-tests # Garante que este job seja executado após o job run-tests
+    needs: run-tests
     steps:
       - name: Checkout
         uses: actions/checkout@v3
-
+  
       - name: Restore node_modules
         uses: actions/cache@v2
         with:
           path: node_modules
           key: ${{runner.os}}-${{hashFiles('**/npm.lock')}}
-
+  
       - name: Run ts-prune
-        run: npm run ts-prune --error
+        run: npm run ts-prune
+        continue-on-error: true
+        env:
+          CI: true
+      - run: |
+          if grep -q "Unused exports found" ${GITHUB_WORKSPACE}/prune-report.txt; then
+            echo "Unused exports found, failing the job"
+            exit 1
+          else
+            echo "No unused exports found"
+          fi
